stack:
  services:
    frontend:
      image:
        tag: sha-3e23de8
      replicaCount: 1
      env:
        - name: API_URL_V2
          value: https://graphql.cryoetdataportal.czscience.com/graphql
        - name: ENV
          value: prod
