stack:
  services:
    frontend:
      image:
        tag: sha-b50f413
      replicaCount: 1
      env:
        - name: API_URL_V2
          value: https://graphql.cryoet.staging.si.czi.technology/graphql
        - name: ENV
          value: dev
