name: HelmDep Update

on:
  workflow_dispatch:
  schedule:
    - cron: "14 7 * * *"

jobs:
  helm_dependency_update:
    uses: chanzuckerberg/github-actions/.github/workflows/argus-helm-chart-update.yaml@v6
    secrets: inherit