name: Docker Image Build

on:
  workflow_call:
    inputs:
      envs:
        description: "Env names, comma delimited"
        required: true
        type: string
      path_filters:
        description: "Glob patterns to match against changed files in the repository, comma delimited"
        required: true
        type: string
      branches_include:
        description: "Branches to build on, comma delimited"
        required: false
        type: string
        default: "*"
      branches_ignore:
        description: "Branches to skip build on, comma delimited"
        required: false
        type: string
        default: ""
      force_update_manifests:
        description: "Whether to always update ArgoCD manifests after building the Docker images"
        required: false
        type: boolean
        default: false

jobs:
  argus_builder:
    uses: chanzuckerberg/github-actions/.github/workflows/argus-docker-build.yaml@v6
    secrets: inherit
    with:
      branches_include: ${{ inputs.branches_include }}
      branches_ignore: ${{ inputs.branches_ignore }}
      force_update_manifests: ${{ inputs.force_update_manifests }}
      path_filters: ${{ inputs.path_filters }}
      envs: ${{ inputs.envs }}
      images: |
        {
          "frontend": {
            "context": "frontend",
            "dockerfile": "frontend/packages/data-portal/Dockerfile"
          }
        }
